repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.10
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
        stages: [commit]
      # Run the formatter.
      - id: ruff-format
        stages: [commit]
