table_of_contents:
  en:
    - table of contents
    - contents
    - index
    - overview
    - summary
    - list of topics
  de:
    - inhalt
    - inhaltsverzeichnis
    - übersicht
    - index
    - zusammenfassung
    - kapitelübersicht
  fr:
    - table des matières
    - sommaire
    - index
    - aperçu
    - résumé
  it:
    - liste des chapitres
    - contenuto
    - indice dei contenuti
    - panoramica
    - indice
    - sommario
    - panoramica dei capitoli

caption_description:
  boreprofile:
    en:
      must_contain:
        - [ profile, log, lithostratigraphy ]
        - [ borehole, drilling, bore ]
    de:
      must_contain:
        - [ profil, log, lithostratigraphie]
        - [ bohrung, bohrloch, bohr ]
    fr:
      must_contain:
        - [ profil, log, lithostratigraphique ]
        - [ forage, sondage ]
    it:
      must_contain:
        - [ profilo, log, stratigrafico, diagramma ]
        - [ perforazione, sondaggio ]

boreprofile:
  en:
    - borehole profile
    - boreprofile
    - borehole
  de:
    - bohrprofil
    - bohrlochprofil
    - bohrung
  fr:
    - forage
    - sondage
  it:
    - profilo di perforazione
    - perforazione
    - sondaggio

material_description:
  de:
    including_expressions:
      - sand
      - silt
      - kies
      - asphalt
      - humus
      - braun
      - grau
      - weich
      - hart
      - wurzel
      - belag
      - stein
      - beige
      - beton
      - kreide
      - mergel
      - kernmaterial
      - dito
    excluding_expressions:
      - herr
      - ende
      - profil
      - beschreibung
      - signaturen
      - mischprobe
      - projekt
      - ort
      - adresse
      - wetter
      - pumpversuch
      - kernbohrung
      - bohrradius

  fr:
    including_expressions:
      - sol
      - végétal  # remove accents generally; ocr might be wrong
      - dallage
      - terre
      - bitume
      - bitumineux
      - grave d'infrastructure  # what happens if we remove this?
      - sable
      - limon
      - gravier
      - asphalte
      - humus  # hummus maybe?
      - brun
      - gris
      - grise
      - mou
      - dur
      - dure
      - ferme
      - racine
      - revetement
      - pierre
      - beige
      - beton
      - craie
      - marne
      - materiau
      - matrice sableuse
      - enrobé  # accent --> check what happens if it's removed
      - terrain
      - remblais
      - remblai
      - molasse
      - phase
      - formations
      - limoneuse
      - argileuse
      - argileux
      - mousse
    excluding_expressions:
      - monsieur
      - fin
      - profil
      - description
      - signatures
      - echantillon mixte
      - projet
      - lieu
      - adresse
      - temps
      - essai de pompage
      - carottage
      - rayon de forage
      - remarque
      - piezometre
      - profondeur
      - désignation

  it:
    including_expressions:
      - sabbia
      - limo
      - ghiaia
      - asfalto
      - humus
      - marrone
      - grigio
      - morbido
      - duro
      - radice
      - rivestimento
      - pietra
      - beige
      - cemento
      - gesso
      - marna
      - materiale di carota
      - idem

    excluding_expressions:
      - signore
      - fine
      - profilo
      - descrizione
      - legende
      - campione misto
      - progetto
      - luogo
      - indirizzo
      - meteo
      - prova di pompaggio
      - carotaggio
      - raggio di perforazione


  en:
    including_expressions:
      - sand
      - sandy
      - sandstone
      - silt
      - silty
      - siltstone
      - clay
      - claystone
      - gravel
      - asphalt
      - humus
      - brown
      - gray
      - soft
      - hard
      - root
      - surface layer
      - stone
      - beige
      - concrete
      - chalk
      - marl
      - core material
      - limestone
      - ditto
      - alternation
      - leucosome
    excluding_expressions:
      - Mr.
      - end
      - profile
      - description
      - signatures
      - mixed sample
      - project
      - location
      - address
      - weather
      - pump test
      - core drilling
      - drilling radius

map_terms:
  en:
    including_expressions:
      - legend
      - map
      - map key
      - map symbols
      - features
      - scale
      - sheet
      - contour interval
      - topographic
      - elevation
    excluding_expressions:
      - diagram
      - graph
      - table
      - chart
  de:
    including_expressions:
      - legende
      - karte
      - kartenzeichen
      - massstab
      - blatt
      - höhenlinien
      - topographisch
      - höhe
      - situation
    excluding_expressions:
      - diagramm
      - grafik
      - tabelle
      - schaubild
      - bohrprofil
  fr:
    including_expressions:
      - carte
      - légende
      - symboles
      - échelle
      - planche
      - courbes de niveau
      - altitude
      - topographique
      - situation
    excluding_expressions:
      - diagramme
      - graphique
      - tableau
      - schéma
  it:
    including_expressions:
      - mappa
      - legenda
      - simboli
      - scala
      - foglio
      - equidistanza
      - curve di livello
      - altimetrico
      - situazione
    excluding_expressions:
      - diagramma
      - grafico
      - tabella
      - schema

title_page:
  en:
    - project
    - report
  de:
    - projekt
    - bericht
  fr:
    - projet
    - rapport
  it:
    - rapporto
    - progetto

diagram:
  en:
    - diagram
    - curve
    - distribution
    - histogram
    - summation curve
    - cumulative curve
    - grading curve
  de:
    - kurve
    - diagramm
    - kornverteilung
    - histogramm
    - summationskurve
    - körnungslinie
    - verteilungskurve
  fr:
    - diagramme
    - courbe
    - distribution
    - histogramme
    - courbe de sommation
    - courbe granulométrique
  it:
    - diagramma
    - curva
    - distribuzione
    - istogramma
    - curva cumulativa
    - curva granulometrica

units:
  - m
  - cm
  - mm
  - µm
  - nm
  - km
  - g
  - kg
  - mg
  - t
  - mol
  - mol/l
  - mol/m3
  - kg/m3
  - g/cm3
  - °c
  - k
  - pa
  - kpa
  - mpa
  - bar
  - l
  - ml
  - l/s
  - m/s
  - s
  - sec
  - h
  - ora