block_line_ratio: 0.20
min_block_clearance: 10
left_line_length_threshold: 7
duplicate_layer_threshold: 0.95
min_num_layers: 2
affinity_params:
  a_above_b:
    importance: 5.0
    weights:
      line_weight: 3.5
      left_line_weight: 1.0
      spacing_weight: 1.25
      right_end_weight: 1.0
      diagonal_weight: 1.25
      gap_weight: 0.0
      indentation_weight: 0.6
  a_to_b:
    importance: 2.0
    weights:
      line_weight: 1.0
      left_line_weight: 1.0
      spacing_weight: 1.0
      right_end_weight: 1.0
      diagonal_weight: 0.0
      gap_weight: 0.0
      indentation_weight: 0.0
  layer_identifier:
    importance: 0.66
    weights:
      line_weight: 0.2
      left_line_weight: 0.2
      spacing_weight: 1.0
      right_end_weight: 0.6
      diagonal_weight: 0.0
      gap_weight: 0.0
      indentation_weight: 0.0
  spulprobe:
    importance: 2.0
    weights:
      line_weight: 1.0
      left_line_weight: 1.0
      spacing_weight: 1.0
      right_end_weight: 1.0
      diagonal_weight: 0.0
      gap_weight: 0.0
      indentation_weight: 0.0
  no_sidebar:
    weights:
      line_weight: 1.0
      left_line_weight: 1.0
      spacing_weight: 1.0
      right_end_weight: 1.0
      diagonal_weight: 1.0
      gap_weight: 0.2
      indentation_weight: 0.0
empty_interval_penalty: 0.2


material_description_column_width: 0.08

depth_column_params:  # these params should be optimized as soon as there is reliable evaluation data
  noise_count_threshold: 1.25
  noise_count_offset: 2.5

non_description_lines_ratio: 0.15

default_language: de

compound_split_threshold: 0.4

table_of_contents:
  en:
    - table of contents
    - contents
    - index
    - overview
    - summary
    - list of topics
  de:
    - inhalt
    - inhaltsverzeichnis
    - übersicht
    - index
    - zusammenfassung
    - kapitelübersicht
  fr:
    - table des matières
    - sommaire
    - index
    - aperçu
    - résumé
  it:
    - liste des chapitres
    - contenuto
    - indice dei contenuti
    - panoramica
    - indice
    - sommario
    - panoramica dei capitoli

caption_description:
  boreprofile:
    en:
      must_contain:
        - [ profile, log, lithostratigraphy ]
        - [ borehole, drilling, bore ]
    de:
      must_contain:
        - [ profil, log, lithostratigraphie]
        - [ bohrung, bohrloch, bohr ]
    fr:
      must_contain:
        - [ profil, log, lithostratigraphique ]
        - [ forage, sondage ]
    it:
      must_contain:
        - [ profilo, log, stratigrafico, diagramma ]
        - [ perforazione, sondaggio ]

boreprofile:
  en:
    - borehole profile
    - boreprofile
    - borehole
  de:
    - bohrprofil
    - bohrlochprofil
    - bohrung
  fr:
    - forage
    - sondage
  it:
    - profilo di perforazione
    - perforazione
    - sondaggio

material_description:
  de:
    including_expressions:
      - sand
      - sandig
      - silt
      - siltig
      - siltstein
      - kies
      - kiesig
      - ton
      - tonig
      - asphalt
      - asphaltdeckschicht # is not split by the compound splitter
      - humus
      - braun
      - weich
      - wurzel
      - belag
      - stein
      - beige
      - beton
      - kreide
      - mergel
      - kern
      - lehm
      - dito
      - dolomit
      - kristallin
      - gneis
      - kalke
      - mikritisch
      - laminiert
      - grob
      - auffüllung
      - schlacke
    excluding_expressions:
      - herr
      - ende
      - profil
      - beschreibung
      - materialbeschreibung
      - kiesprospektion
      - signaturen
      - mischprobe # Should be reviewed, currently not used
      - projekt
      - ort
      - adresse
      - wetter
      - pumpversuch
      - kernbohrung
      - bohrradius # Should be reviewed, currently not used
      - wasserzutritt
      - Vollrohr
      - Filterrohr

  fr:
    including_expressions:
      - sol
      - végétal
      - dallage
      - terre
      - bitume
      - bitumineux
      - grave d'infrastructure  # Should be reviewed, currently not used
      - sable
      - limon
      - gravier
      - asphalte
      - humus
      - brun
      - gris
      - grise
      - mou
      - dur
      - dure
      - ferme
      - racine
      - revetement
      - pierre
      - beige
      - béton
      - craie
      - marne
      - materiau # Should be reviewed, currently not used
      - matrice sableuse # Should be reviewed, currently not used
      - enrobé
      - phase
      - limoneuse
      - argileuse
      - argileux
      - mousse # Should be reviewed, currently not used
    excluding_expressions:
      - monsieur # Should be reviewed, currently not used
      - profil
      - description
      - signatures # Should be reviewed, currently not used
      - echantillon mixte # Should be reviewed, currently not used
      - projet
      - lieu
      - adresse
      - temps
      - essai de pompage # Should be reviewed, currently not used
      - carottage
      - rayon de forage # Should be reviewed, currently not used
      - remarque
      - piezometre
      - profondeur
      - désignation

  en:
    including_expressions:
      - sand
      - sandy
      - sandstone
      - silt
      - silty
      - siltstone
      - clay
      - claystone
      - gravel
      - asphalt
      - humus
      - brown
      - gray
      - soft
      - hard
      - root
      - surface layer
      - stone
      - beige
      - concrete
      - chalk
      - marl
      - core material
      - limestone
      - ditto # Should be reviewed, currently not used
      - alternation
      - leucosome
    excluding_expressions:
      - Mr.
      - end
      - profile
      - description
      - signatures
      - mixed sample
      - project
      - location
      - address
      - weather
      - pump test # Should be reviewed, currently not used
      - core drilling
      - drilling radius

map_terms:
  en:
    including_expressions:
      - legend
      - map
      - map key
      - map symbols
      - features
      - scale
      - sheet
      - contour interval
      - topographic
      - elevation
    excluding_expressions:
      - diagram
      - graph
      - table
      - chart
  de:
    including_expressions:
      - legende
      - karte
      - kartenzeichen
      - massstab
      - blatt
      - höhenlinien
      - topographisch
      - höhe
      - situation
    excluding_expressions:
      - diagramm
      - grafik
      - tabelle
      - schaubild
      - bohrprofil
  fr:
    including_expressions:
      - carte
      - légende
      - symboles
      - échelle
      - planche
      - courbes de niveau
      - altitude
      - topographique
      - situation
    excluding_expressions:
      - diagramme
      - graphique
      - tableau
      - schéma
  it:
    including_expressions:
      - mappa
      - legenda
      - simboli
      - scala
      - foglio
      - equidistanza
      - curve di livello
      - altimetrico
      - situazione
    excluding_expressions:
      - diagramma
      - grafico
      - tabella
      - schema

title_page:
  en:
    - project
    - report
  de:
    - projekt
    - bericht
  fr:
    - projet
    - rapport
  it:
    - rapporto
    - progetto

geo_profile:
  en:
    - geological cross-section
    - geological section
    - geological profile
    - cross-section
    - vertical section
  de:
    - längsprofil
    - längenprofil
    - geologischer schnitt
    - geologisches profil
    - vertikalschnitt
  fr:
    - coupe géologique
    - profil géologique
    - section géologique
    - coupe en profondeur
    - coupe verticale
    - coupe longitudinale
  it:
    - sezione geologica
    - profilo geologico
    - sezione verticale
    - taglio geologico


diagram:
  en:
    - diagram
    - curve
    - distribution
    - histogram
    - summation curve
    - cumulative curve
    - grading curve
  de:
    - kurve
    - diagramm
    - kornverteilung
    - histogramm
    - summationskurve
    - körnungslinie
    - verteilungskurve
  fr:
    - diagramme
    - courbe
    - distribution
    - histogramme
    - courbe de sommation
    - courbe granulométrique
  it:
    - diagramma
    - curva
    - distribuzione
    - istogramma
    - curva cumulativa
    - curva granulometrica

units:
  - m
  - cm
  - mm
  - µm
  - nm
  - km
  - g
  - kg
  - mg
  - t
  - mol
  - mol/l
  - mol/m3
  - kg/m3
  - g/cm3
  - °c
  - k
  - pa
  - kpa
  - mpa
  - bar
  - l
  - ml
  - l/s
  - m/s
  - s
  - sec
  - h
  - ora

open_ended_depth_key:
  - ab
  - des
  - dès
  - a partir de
  - à partir de
  - from
  - starting at
  - a partire