model_type: xgboost

train_folder_path: "data/single_pages_splits/train"
val_folder_path: "data/single_pages_splits/val"
ground_truth_file_path: "data/gt_single_pages.json"

# Feature names to track
feature_names:
  - Words Per Line
  - Text zone Density
  - Mean Left
  - Text Width
  - Line Count
  - Indent Std Dev
  - Capitalization Ratio
  - Has Sidebar
  - Has Borehole Keyword
  - Num Valid Material Descriptions
  - Num Map Keyword Lines
  - Grid Line Length Sum
  - Non Grid Line Length Sum
  - Line Angle Entropy
  - Line score
  - Num Geo Profile Keywords
  - Num Unit Keyword
  - Y scale ok
  - X scale ok


hyperparameters:
  n_estimators: 500
  max_depth: 5
  learning_rate: 0.05
  subsample: 0.8
  colsample_bytree: 1
  eval_metric: mlogloss

tuning:
  n_iter: 50
  cv: 3
  param_grid:
    n_estimators: [100, 200, 300, 400, 500, 600]
    max_depth: [4, 5, 6, 7]
    learning_rate: [0.01, 0.05, 0.1, 0.3]
    subsample: [0.6, 0.8, 1.0]
    colsample_bytree: [0.6, 0.8, 1.0]