name: pipeline_run

on:
  pull_request:
  push:
    branches: [main]

env:
  MLFLOW_TRACKING: "False"
  FASTTEXT_MODEL_PATH: models/FastText/lid.176.bin

jobs:
  pipeline_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies and run pipeline
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install .
        echo "Download FastText model"
        mkdir -p models/FastText
        curl -o models/FastText/lid.176.bin https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.bin
        echo "Running pipeline with baseline classifier"
        python main.py -i examples/example_pdf.pdf -c baseline

        
